---
- name: ServicesVM Installation
  hosts: localhost
  remote_user: root
  become: true
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - firewalld
        - apache2
        - net-tools
        - samba
        - php
        - php-cgi
        - php-mysqli
        - php-pear
        - php-curl
        - php-gd
        - php-xml
        - php-xmlrpc
        - php-soap
        - php-intl
        - php-zip
        - php-mbstring
        - php-gettext
        - libapache2-mod-php
        - php-common
        - php-phpseclib
        - php-mysql
        - openssh-server
